### ISSUE TITLE
Modificar texto modelo de pase a fallo

### ISSUE THREAD

**Issue by fhatzen** [fhatzen/copetel#4]
Modificar texto modelo de pase a fallo (se mandó adjunto el texto que tiene que ir).

**Comment by fhatzen** [comment]
Pasame el texto modelo, gracias

**Comment by Angelica2015** [comment]
No me deja cargar el modelo, no reconoce el tipo de archivo

**Comment by fhatzen** [comment]
Toma sólo imágenes. 

En este caso, vos deberías (1) pegar el texto en esta ventana y (2) cambiar el "asignee" de Angelica2015 a fhatzen, para que pase a "mi" lista de pendientes. Probalo así hacemos el ciclo completo y pasamos a nivel 2. Pega un texto aquí y cambia el asignee.

**Comment by Angelica2015** [comment]
CERTIFICADO DE DEUDA

El  Bolsón 05 de junio de 2013,-
Por la presente se certifica que en los autos caratulados “Martínez Vera David psi Art. xxx” Expte. Nº 922/T2012 en trámite por ante el Juzgado de Faltas de la localidad de El Bolsón, sito en Perito Moreno 3560 de esta ciudad, a mi cargo, se ha dictado la Sentencia Nº  566/2012, notificada en fecha 21 de septiembre de 2012, la cual se encuentra firme y consentida.------------------------------------------------------
Que se ha impuesto pena de multa de pesos mil ochenta ($ 1080,-), con más la suma de pesos cuarenta y cinco ($ 45,-) en concepto de tasa de actuación al Sr. Martínez Vera David DNI Nº 15,496,328 domiciliado en Cacique Foyel y Miguel Anden de la localidad de El Bolsón provincia de Río Negro, y verificados los datos en el sistema operativo de la municipalidad de El Bolsón, no se encuentra registrado el pago al día de la fecha.---------------------------------------------------------------------------------------------------
Se emite el presente certificado en los términos del artículo 213 de la Odza. 161/2011 (texto cfme Odza. 025/2012).-----------------------------------------------------------------------------

**Comment by fhatzen** [comment]
Modificado en el sistema el texto modelo
